[project]
name = "control-engineering-with-python-project-2023-2024"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
start = "jupyter lab"

[dependencies]
python = "==3.12"
jupyterlab = ">=4.2.0,<4.3"
matplotlib = ">=3.8.4,<3.9"
numpy = ">=1.26.4,<1.27"
scipy = ">=1.13.0,<1.14"
